# -*- coding: utf-8 -*-
"""Algorithmic trading(Moving Average).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OC0flcfeuGfg5_qUuEUkj4DOAeWjhYaT
"""

pip install yfinance

import datetime as dt
import matplotlib.pyplot as plt
import pandas_datareader as web
from pandas_datareader import data as pdr
import yfinance as yf

plt.style.use("dark_background")

#The unit of moving average is "Day" 
#and you can change the first and second moving average to your time frames
first_moving_average = 30
second_moving_average = 100

start = dt.datetime.now() - dt.timedelta(days=365 * 3)
end = dt.datetime.now()

yf.pdr_override()

#You can replace the symbol with others like "FB" or "ETH-USD" or TSLA
symbol = "AMZN"

data = pdr.get_data_yahoo(symbol, start, end)

data[f'SMA_{first_moving_average}'] = data['Adj Close'].rolling(window = first_moving_average).mean()
data[f'SMA_{second_moving_average}'] = data['Adj Close'].rolling(window=ma_2).mean()

data = data.iloc[ma_2:]

plt.plot(data['Adj Close'], label="Share Price",color="lightgray")
plt.plot(data[f'SMA_{first_moving_average}'], label=f"SMA_{first_moving_average}", color="orange")
plt.plot(data[f'SMA_{second_moving_average}'], label=f"SMA_{second_moving_average}", color="purple")
plt.legend(loc="upper left")
plt.show()

buy_signals = []
sell_signals = []
trigger = 0

for x in range(len(data)):

  if data[f'SMA_{first_moving_average}'].iloc[x] > data[f'SMA_{second_moving_average}'].iloc[x] and trigger != 1:
    buy_signals.append(data['Adj Close'].iloc[x])
    sell_signals.append(float('nan'))
    trigger = 1

  elif data[f'SMA_{first_moving_average}'].iloc[x] < data[f'SMA_{second_moving_average}'].iloc[x] and trigger != -1:
    buy_signals.append(float('nan'))
    sell_signals.append(data['Adj Close'].iloc[x])
    trigger = -1

  else:
    buy_signals.append(float('nan'))
    sell_signals.append(float('nan'))

data['Buy Signals'] = buy_signals
data['Sell Signals'] = sell_signals

print(data)

plt.plot(data['Adj Close'], label="Share Price",alpha=0.5)
plt.plot(data[f'SMA_{first_moving_average}'], label=f"SMA_{first_moving_average}", color="orange", linestyle="--")
plt.plot(data[f'SMA_{second_moving_average}'], label=f"SMA_{second_moving_average}", color="pink", linestyle="--")
plt.scatter(data.index, data['Buy Signals'], label="Buy Signal", marker="^", color="#00ff00", lw=3)
plt.scatter(data.index, data['Sell Signals'], label="Sell Signal", marker="v", color="#ff0000", lw=3)
plt.legend(loc="upper left")
plt.show()
plt.rcParams["figure.figsize"] = (20,4)

"""**Red points** are sell signals and it is recommanded by algorithm to sell on these points.

On the other hand, **Green points** are buy signals and it is recommanded by algorithm to buy on those points.
"""